# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  matrix:
#    - nodejs_version: "0.10"
#    - nodejs_version: "0.12"

#    - nodejs_version: "3"
#    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "9"

matrix:
  fast_finish: true

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
# Temporaily fix for node 9
#  - npm install -g npm@5.3
  - npm install

cache:
  - node_modules -> package.json

skip_commits:
  files:
    - docs/*
    - '*.md'

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Run tests
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
